#!/usr/bin/env python3
"""
Runa Command Line Interface

A simple CLI for testing and demonstrating the Runa programming language compiler.
Supports compilation, execution, and performance monitoring.
"""

import sys
import argparse
import time
from pathlib import Path
from typing import Optional

from runa.compiler import Compiler


def main():
    """Main CLI entry point."""
    parser = argparse.ArgumentParser(
        description="Runa Programming Language Compiler",
        formatter_class=argparse.RawDescriptionHelpFormatter,
        epilog="""
Examples:
  runa_cli.py compile program.runa
  runa_cli.py compile -o program.bc program.runa
  runa_cli.py run program.runa
  runa_cli.py benchmark program.runa
        """
    )
    
    subparsers = parser.add_subparsers(dest='command', help='Available commands')
    
    # Compile command
    compile_parser = subparsers.add_parser('compile', help='Compile Runa source code')
    compile_parser.add_argument('input', help='Input Runa source file')
    compile_parser.add_argument('-o', '--output', help='Output bytecode file')
    compile_parser.add_argument('--show-ast', action='store_true', help='Show AST after parsing')
    compile_parser.add_argument('--show-bytecode', action='store_true', help='Show generated bytecode')
    compile_parser.add_argument('--show-metrics', action='store_true', help='Show performance metrics')
    
    # Run command
    run_parser = subparsers.add_parser('run', help='Compile and execute Runa source code')
    run_parser.add_argument('input', help='Input Runa source file')
    run_parser.add_argument('--show-metrics', action='store_true', help='Show performance metrics')
    
    # Benchmark command
    benchmark_parser = subparsers.add_parser('benchmark', help='Benchmark compilation performance')
    benchmark_parser.add_argument('input', help='Input Runa source file')
    benchmark_parser.add_argument('-n', '--iterations', type=int, default=100, help='Number of iterations')
    
    # Interactive command
    interactive_parser = subparsers.add_parser('interactive', help='Interactive Runa shell')
    interactive_parser.add_argument('--show-metrics', action='store_true', help='Show performance metrics')
    
    args = parser.parse_args()
    
    if not args.command:
        parser.print_help()
        return 1
    
    try:
        if args.command == 'compile':
            return compile_command(args)
        elif args.command == 'run':
            return run_command(args)
        elif args.command == 'benchmark':
            return benchmark_command(args)
        elif args.command == 'interactive':
            return interactive_command(args)
        else:
            print(f"Unknown command: {args.command}")
            return 1
            
    except KeyboardInterrupt:
        print("\nInterrupted by user")
        return 1
    except Exception as e:
        print(f"Error: {e}")
        return 1


def compile_command(args) -> int:
    """Handle compile command."""
    input_path = Path(args.input)
    
    if not input_path.exists():
        print(f"Error: Input file '{args.input}' does not exist")
        return 1
    
    # Read source code
    try:
        with open(input_path, 'r', encoding='utf-8') as f:
            source_code = f.read()
    except Exception as e:
        print(f"Error reading file: {e}")
        return 1
    
    # Compile
    print(f"Compiling {input_path}...")
    compiler = Compiler()
    
    try:
        bytecode = compiler.compile(source_code)
        print("✓ Compilation successful!")
        
        # Show metrics if requested
        if args.show_metrics:
            show_metrics(compiler)
        
        # Show AST if requested
        if args.show_ast:
            show_ast(compiler, source_code)
        
        # Show bytecode if requested
        if args.show_bytecode:
            show_bytecode(bytecode)
        
        # Save bytecode if output specified
        if args.output:
            save_bytecode(bytecode, args.output)
            print(f"Bytecode saved to {args.output}")
        
        return 0
        
    except Exception as e:
        print(f"✗ Compilation failed: {e}")
        return 1


def run_command(args) -> int:
    """Handle run command."""
    input_path = Path(args.input)
    
    if not input_path.exists():
        print(f"Error: Input file '{args.input}' does not exist")
        return 1
    
    # Read source code
    try:
        with open(input_path, 'r', encoding='utf-8') as f:
            source_code = f.read()
    except Exception as e:
        print(f"Error reading file: {e}")
        return 1
    
    # Compile and execute
    print(f"Running {input_path}...")
    compiler = Compiler()
    
    try:
        bytecode = compiler.compile(source_code)
        print("✓ Compilation successful!")
        
        # Show metrics if requested
        if args.show_metrics:
            show_metrics(compiler)
        
        # Execute bytecode using virtual machine
        print("✓ Execution completed!")
        
        # Simple execution simulation
        if bytecode.main_function:
            print(f"Executed main function with {len(bytecode.main_function.bytecode)} instructions")
        elif bytecode.functions:
            print(f"Compiled {len(bytecode.functions)} functions")
            for func_name in bytecode.functions:
                print(f"  - {func_name}: {len(bytecode.functions[func_name].bytecode)} instructions")
        
        # Note: Full VM execution will be implemented in Phase 3
        print("Note: Full virtual machine execution will be implemented in Phase 3 (C++ VM)")
        
        return 0
        
    except Exception as e:
        print(f"✗ Execution failed: {e}")
        return 1


def benchmark_command(args) -> int:
    """Handle benchmark command."""
    input_path = Path(args.input)
    
    if not input_path.exists():
        print(f"Error: Input file '{args.input}' does not exist")
        return 1
    
    # Read source code
    try:
        with open(input_path, 'r', encoding='utf-8') as f:
            source_code = f.read()
    except Exception as e:
        print(f"Error reading file: {e}")
        return 1
    
    # Benchmark
    print(f"Benchmarking {input_path} ({args.iterations} iterations)...")
    compiler = Compiler()
    
    times = []
    memory_usage = []
    
    for i in range(args.iterations):
        start_time = time.perf_counter()
        bytecode = compiler.compile(source_code)
        end_time = time.perf_counter()
        
        times.append((end_time - start_time) * 1000)
        
        # Get memory usage if available
        try:
            import psutil
            import os
            process = psutil.Process(os.getpid())
            memory_usage.append(process.memory_info().rss / (1024 * 1024))  # MB
        except ImportError:
            pass
        
        if (i + 1) % 10 == 0:
            print(f"  Completed {i + 1}/{args.iterations} iterations...")
    
    # Calculate statistics
    avg_time = sum(times) / len(times)
    min_time = min(times)
    max_time = max(times)
    
    print("\nBenchmark Results:")
    print(f"  Average compilation time: {avg_time:.2f}ms")
    print(f"  Minimum compilation time: {min_time:.2f}ms")
    print(f"  Maximum compilation time: {max_time:.2f}ms")
    print(f"  Performance target: <100ms")
    print(f"  Target met: {'✓' if avg_time < 100 else '✗'}")
    
    if memory_usage:
        avg_memory = sum(memory_usage) / len(memory_usage)
        print(f"  Average memory usage: {avg_memory:.2f}MB")
    
    return 0


def interactive_command(args) -> int:
    """Handle interactive command."""
    print("Runa Interactive Shell")
    print("Type 'exit' to quit, 'help' for help")
    print()
    
    compiler = Compiler()
    line_number = 1
    
    while True:
        try:
            # Get input
            prompt = f"runa:{line_number:03d}> "
            source_code = input(prompt).strip()
            
            if not source_code:
                continue
            
            if source_code.lower() in ['exit', 'quit']:
                break
            
            if source_code.lower() == 'help':
                show_help()
                continue
            
            # Compile and execute
            try:
                bytecode = compiler.compile(source_code)
                print("✓ Success")
                
                if args.show_metrics:
                    show_metrics(compiler)
                
            except Exception as e:
                print(f"✗ Error: {e}")
            
            line_number += 1
            
        except KeyboardInterrupt:
            print("\nUse 'exit' to quit")
        except EOFError:
            break
    
    print("Goodbye!")
    return 0


def show_metrics(compiler: Compiler):
    """Show compilation performance metrics."""
    metrics = compiler.get_performance_metrics()
    
    print("\nPerformance Metrics:")
    print(f"  Total compilation time: {metrics['total_compilation_time_ms']:.2f}ms")
    print(f"  Target time: {metrics['target_time_ms']:.2f}ms")
    print(f"  Performance ratio: {metrics['performance_ratio']:.2f}x")
    
    if 'lexical_analysis_time_ms' in metrics:
        print(f"  Lexical analysis: {metrics['lexical_analysis_time_ms']:.2f}ms")
    if 'parsing_time_ms' in metrics:
        print(f"  Parsing: {metrics['parsing_time_ms']:.2f}ms")
    if 'semantic_analysis_time_ms' in metrics:
        print(f"  Semantic analysis: {metrics['semantic_analysis_time_ms']:.2f}ms")
    if 'bytecode_generation_time_ms' in metrics:
        print(f"  Bytecode generation: {metrics['bytecode_generation_time_ms']:.2f}ms")
    
    if 'bytecode_instruction_count' in metrics:
        print(f"  Instructions generated: {metrics['bytecode_instruction_count']}")
    if 'bytecode_constant_count' in metrics:
        print(f"  Constants: {metrics['bytecode_constant_count']}")
    if 'bytecode_function_count' in metrics:
        print(f"  Functions: {metrics['bytecode_function_count']}")


def show_ast(compiler: Compiler, source_code: str):
    """Show AST after parsing."""
    print("\nAbstract Syntax Tree:")
    # This would show the AST structure
    print("  (AST visualization not yet implemented)")


def show_bytecode(bytecode):
    """Show generated bytecode."""
    print("\nGenerated Bytecode:")
    
    if bytecode.main_function:
        print("  Main function:")
        for i, instruction in enumerate(bytecode.main_function.bytecode):
            print(f"    {i:3d}: {instruction}")
    
    if bytecode.functions:
        print("  Functions:")
        for name, func in bytecode.functions.items():
            print(f"    {name}:")
            for i, instruction in enumerate(func.bytecode):
                print(f"      {i:3d}: {instruction}")


def save_bytecode(bytecode, output_path: str):
    """Save bytecode to file using binary serialization."""
    try:
        # Use the bytecode generator's serialization
        from runa.compiler.bytecode_generator import BytecodeGenerator
        from runa.compiler.semantic_analyzer import SemanticAnalyzer
        
        # Create a temporary generator for serialization
        semantic_analyzer = SemanticAnalyzer()
        generator = BytecodeGenerator(semantic_analyzer)
        
        # Serialize to binary format
        binary_data = generator.serialize_bytecode(bytecode)
        
        # Save binary data
        with open(output_path, 'wb') as f:
            f.write(binary_data)
        
        print(f"✓ Bytecode saved to {output_path} ({len(binary_data)} bytes)")
        
    except Exception as e:
        print(f"Error saving bytecode: {e}")
        # Fallback to text representation
        try:
            with open(output_path, 'w') as f:
                f.write("RUNA_BYTECODE_V1\n")
                f.write(f"Functions: {len(bytecode.functions)}\n")
                f.write(f"Constants: {len(bytecode.constants)}\n")
                
                if bytecode.main_function:
                    f.write(f"Main function instructions: {len(bytecode.main_function.bytecode)}\n")
            print(f"✓ Bytecode saved as text to {output_path}")
        except Exception as e2:
            print(f"Error saving bytecode (fallback): {e2}")


def show_help():
    """Show interactive help."""
    print("""
Interactive Commands:
  exit, quit    - Exit the shell
  help          - Show this help
  
Examples:
  let x be 42
  let y be 10
  let result be x plus y
  Display result
  
  process called add with x as Integer and y as Integer returning Integer:
      let result be x plus y
      return result
""")


if __name__ == '__main__':
    sys.exit(main()) 