#!/usr/bin/env python3
"""
Simple test script for Runa compiler
"""

import sys
import os

# Add current directory to path
sys.path.insert(0, os.path.dirname(os.path.abspath(__file__)))

from src.runa.compiler import Compiler, Lexer, Parser, SemanticAnalyzer, BytecodeGenerator

def test_lexer():
    """Test basic lexer functionality."""
    print("Testing Lexer...")
    
    source = "Let x be 42"
    
    try:
        lexer = Lexer(source)
        tokens = lexer.tokenize()
        print(f"✓ Lexer: Generated {len(tokens)} tokens")
        for i, token in enumerate(tokens):
            print(f"  {i}: {token.type.name} = '{token.value}'")
        return True
    except Exception as e:
        print(f"✗ Lexer failed: {e}")
        return False

def test_parser():
    """Test basic parser functionality."""
    print("\nTesting Parser...")
    
    source = "Let x be 42"
    
    try:
        lexer = Lexer(source)
        tokens = lexer.tokenize()
        parser = Parser(tokens)
        ast = parser.parse()
        print(f"✓ Parser: Generated AST with {len(ast.statements)} statements")
        return True
    except Exception as e:
        print(f"✗ Parser failed: {e}")
        return False

def test_semantic_analyzer():
    """Test basic semantic analyzer functionality."""
    print("\nTesting Semantic Analyzer...")
    
    analyzer = SemanticAnalyzer()
    source = "Let x be 42"
    
    try:
        parser = Parser()
        tokens = parser.lexer.tokenize(source)
        ast = parser.parse(tokens)
        
        success = analyzer.analyze(ast)
        print(f"✓ Semantic Analyzer: Analysis {'succeeded' if success else 'failed'}")
        return success
    except Exception as e:
        print(f"✗ Semantic Analyzer failed: {e}")
        return False

def test_bytecode_generator():
    """Test basic bytecode generator functionality."""
    print("\nTesting Bytecode Generator...")
    
    try:
        analyzer = SemanticAnalyzer()
        generator = BytecodeGenerator(analyzer)
        source = "Let x be 42"
        
        parser = Parser()
        tokens = parser.lexer.tokenize(source)
        ast = parser.parse(tokens)
        
        analyzer.analyze(ast)
        bytecode = generator.generate(ast)
        
        print(f"✓ Bytecode Generator: Generated bytecode with {len(bytecode.main_function.bytecode)} instructions")
        return True
    except Exception as e:
        print(f"✗ Bytecode Generator failed: {e}")
        return False

def test_full_compiler():
    """Test complete compiler pipeline."""
    print("\nTesting Full Compiler...")
    
    compiler = Compiler()
    source = "Let x be 42"
    
    try:
        bytecode = compiler.compile(source)
        print(f"✓ Full Compiler: Successfully compiled to bytecode")
        
        # Show metrics
        metrics = compiler.get_performance_metrics()
        print(f"  Compilation time: {metrics['total_compilation_time_ms']:.2f}ms")
        print(f"  Performance target met: {compiler.validate_performance_target()}")
        
        return True
    except Exception as e:
        print(f"✗ Full Compiler failed: {e}")
        return False

def test_complex_program():
    """Test compilation of a more complex program."""
    print("\nTesting Complex Program...")
    
    compiler = Compiler()
    source = """
    Let x be 42
    Let y be 10
    Let result be x plus y
    Display result
    """
    
    try:
        bytecode = compiler.compile(source)
        print(f"✓ Complex Program: Successfully compiled")
        
        # Show metrics
        metrics = compiler.get_performance_metrics()
        print(f"  Compilation time: {metrics['total_compilation_time_ms']:.2f}ms")
        print(f"  Instructions generated: {metrics.get('bytecode_instruction_count', 'N/A')}")
        
        return True
    except Exception as e:
        print(f"✗ Complex Program failed: {e}")
        return False

def main():
    """Run all tests."""
    print("Runa Compiler Test Suite")
    print("=" * 50)
    
    tests = [
        test_lexer,
        test_parser,
        test_semantic_analyzer,
        test_bytecode_generator,
        test_full_compiler,
        test_complex_program,
    ]
    
    passed = 0
    total = len(tests)
    
    for test in tests:
        try:
            if test():
                passed += 1
        except Exception as e:
            print(f"✗ Test {test.__name__} crashed: {e}")
    
    print("\n" + "=" * 50)
    print(f"Test Results: {passed}/{total} tests passed")
    
    if passed == total:
        print("🎉 All tests passed!")
        return 0
    else:
        print("❌ Some tests failed!")
        return 1

if __name__ == '__main__':
    sys.exit(main()) 