[package]
name = "example-web-framework"
version = "1.2.3"
description = "A natural language web framework for Runa"
type = "library"
author = "Jane Developer"
email = "jane@example.com"
license = "MIT"
homepage = "https://example.com/runa-web"
repository = "https://github.com/example/runa-web"
keywords = ["web", "framework", "http", "server"]
categories = ["web-development", "frameworks"]

[dependencies]
# Simple version constraint
http-client = "^2.1.0"

# Complex dependency with optional features
database-orm = { version = "~1.5", optional = true, registry = "https://custom-registry.com" }

# Git dependency
logging-utils = { git = "https://github.com/runa-lang/logging", branch = "main" }

# Local development dependency
test-framework = { version = "^3.0", type = "development" }

# Path dependency for local development
shared-utilities = { path = "../shared" }

[build]
entry-point = "src/main.runa"
include = ["src/**/*.runa", "assets/**", "README.md", "LICENSE"]
exclude = ["tests/**", "examples/**", "*.tmp"]
build-scripts = [
    "runa compile --optimize",
    "runa bundle --target web"
]
test-command = "runa test --coverage"

[scripts]
# Custom scripts that can be run with 'runa run <script-name>'
start = "runa run src/server.runa --port 8080"
dev = "runa run src/server.runa --port 8080 --debug"
test = "runa test tests/ --verbose"
benchmark = "runa run benchmarks/performance.runa"
deploy = "runa build && docker build -t my-app ."
docs = "runa doc generate --output docs/"

[registry]
# Optional: specify custom registry settings
default = "https://packages.runa-lang.org"
token = "$RUNA_REGISTRY_TOKEN"

[workspace]
# For multi-package workspaces
members = ["packages/*", "tools/*"]
exclude = ["target/", "node_modules/"]

[features]
# Optional features that can be enabled
default = ["json-support", "basic-auth"]
json-support = ["json-parser"]
advanced-auth = ["oauth-client", "jwt-tokens"]
database = ["database-orm"]
all = ["json-support", "advanced-auth", "database"]

[metadata]
# Additional metadata for package registry
documentation = "https://docs.example.com/runa-web"
funding = "https://github.com/sponsors/example"
changelog = "https://github.com/example/runa-web/blob/main/CHANGELOG.md"
minimum-runa-version = "0.5.0"