"""
Ada Code Generator for Runa Universal Translation Platform
Generates Ada 2012 source code with safety-critical formatting

Features:
- SPARK subset compliance
- Defense/aerospace coding standards (MISRA Ada, DO-178C)
- Ravenscar profile support
- Strong typing with constraints
- Package system formatting
- Tasking and protected object generation
- Contract-based programming
"""

from typing import Dict, List, Optional, Any, TextIO
from dataclasses import dataclass
from enum import Enum
import textwrap
import logging

from .ada_ast import *
from ...core.generator_base import BaseGenerator, GenerationError

logger = logging.getLogger(__name__)

class AdaCodeStyle(Enum):
    """Ada coding styles"""
    STANDARD = "standard"          # Standard Ada formatting
    SPARK = "spark"               # SPARK subset compliance
    RAVENSCAR = "ravenscar"       # Ravenscar profile
    DEFENSE = "defense"           # Defense/aerospace standards
    COMPACT = "compact"           # Compact formatting
    VERBOSE = "verbose"           # Verbose with comments

@dataclass
class AdaFormattingOptions:
    """Ada code formatting options"""
    indent_size: int = 3
    max_line_length: int = 79
    use_lowercase_keywords: bool = True
    align_assignments: bool = True
    align_declarations: bool = True
    blank_lines_between_units: int = 2
    comment_column: int = 40
    insert_safety_comments: bool = True
    enforce_spark_restrictions: bool = False
    use_ravenscar_profile: bool = False

class AdaGenerationError(GenerationError):
    """Ada-specific generation error"""
    pass

class AdaGenerator(BaseGenerator):
    """Ada code generator"""
    
    def __init__(self, style: AdaCodeStyle = AdaCodeStyle.STANDARD,
                 options: Optional[AdaFormattingOptions] = None):
        super().__init__("ada")
        self.style = style
        self.options = options or AdaFormattingOptions()
        self.current_indent = 0
        self.required_packages: set = set()
        
    def generate(self, ast_node: AdaNode) -> str:
        """Generate Ada code from AST"""
        try:
            if isinstance(ast_node, AdaCompilationUnit):
                return self.generate_compilation_unit(ast_node)
            elif isinstance(ast_node, AdaPackageSpecification):
                return self.generate_package_specification(ast_node)
            elif isinstance(ast_node, AdaPackageBody):
                return self.generate_package_body(ast_node)
            elif isinstance(ast_node, AdaSubprogramSpecification):
                return self.generate_subprogram_specification(ast_node)
            elif isinstance(ast_node, AdaSubprogramBody):
                return self.generate_subprogram_body(ast_node)
            else:
                return self.generate_generic_node(ast_node)
                
        except Exception as e:
            raise AdaGenerationError(f"Failed to generate Ada code: {e}")
    
    def generate_compilation_unit(self, unit: AdaCompilationUnit) -> str:
        """Generate compilation unit"""
        lines = []
        
        # File header comment
        if self.options.insert_safety_comments:
            lines.extend(self.generate_file_header())
        
        # Context clauses
        for clause in unit.context_clauses:
            lines.append(self.generate_context_clause(clause))
        
        if unit.context_clauses:
            lines.append("")
        
        # Pragmas
        for pragma in unit.pragmas:
            lines.append(self.generate_pragma(pragma))
        
        if unit.pragmas:
            lines.append("")
        
        # Main unit
        lines.append(self.generate(unit.unit))
        
        return "\n".join(lines)
    
    def generate_file_header(self) -> List[str]:
        """Generate safety-critical file header"""
        header = [
            "--" + "=" * 77,
            "-- Ada Source File Generated by Runa Universal Translation Platform",
            "-- Safety-Critical Ada Code - Review Required",
            f"-- Coding Standard: {self.style.value.upper()}",
        ]
        
        if self.options.enforce_spark_restrictions:
            header.append("-- SPARK Subset Compliance: ENFORCED")
        
        if self.options.use_ravenscar_profile:
            header.append("-- Ravenscar Profile: APPLIED")
            
        header.extend([
            "--" + "=" * 77,
            ""
        ])
        
        return header
    
    def generate_context_clause(self, clause: AdaContextClause) -> str:
        """Generate with/use clause"""
        if isinstance(clause, AdaWithClause):
            prefix = ""
            if clause.is_limited:
                prefix = "limited "
            elif clause.is_private:
                prefix = "private "
                
            units = ", ".join(clause.library_units)
            return f"with {prefix}{units};"
            
        elif isinstance(clause, AdaUseClause):
            units = ", ".join(clause.library_units)
            return f"use {units};"
            
        return ""
    
    def generate_pragma(self, pragma: AdaPragma) -> str:
        """Generate pragma directive"""
        if pragma.arguments:
            args = ", ".join(self.generate_expression(arg) for arg in pragma.arguments)
            return f"pragma {pragma.pragma_name} ({args});"
        else:
            return f"pragma {pragma.pragma_name};"
    
    def generate_package_specification(self, pkg: AdaPackageSpecification) -> str:
        """Generate package specification"""
        lines = []
        
        # Package header
        lines.append(f"package {pkg.name} is")
        self.current_indent += 1
        
        # Public declarations
        for decl in pkg.declarations:
            decl_code = self.generate_declaration(decl)
            if decl_code:
                lines.extend(self.indent_lines(decl_code.split('\n')))
                lines.append("")
        
        # Private part
        if pkg.private_declarations:
            lines.append("")
            lines.append("private")
            lines.append("")
            
            for decl in pkg.private_declarations:
                decl_code = self.generate_declaration(decl)
                if decl_code:
                    lines.extend(self.indent_lines(decl_code.split('\n')))
                    lines.append("")
        
        self.current_indent -= 1
        lines.append(f"end {pkg.name};")
        
        return "\n".join(lines)
    
    def generate_package_body(self, body: AdaPackageBody) -> str:
        """Generate package body"""
        lines = []
        
        lines.append(f"package body {body.name} is")
        self.current_indent += 1
        
        # Declarations
        for decl in body.declarations:
            decl_code = self.generate_declaration(decl)
            if decl_code:
                lines.extend(self.indent_lines(decl_code.split('\n')))
                lines.append("")
        
        # Statements
        if body.statements:
            lines.append("")
            lines.append("begin")
            for stmt in body.statements:
                stmt_code = self.generate_statement(stmt)
                if stmt_code:
                    lines.extend(self.indent_lines(stmt_code.split('\n')))
        
        # Exception handlers
        if body.exception_handlers:
            lines.append("")
            lines.append("exception")
            for handler in body.exception_handlers:
                handler_code = self.generate_exception_handler(handler)
                lines.extend(self.indent_lines(handler_code.split('\n')))
        
        self.current_indent -= 1
        lines.append(f"end {body.name};")
        
        return "\n".join(lines)
    
    def generate_subprogram_specification(self, subprog: AdaSubprogramSpecification) -> str:
        """Generate subprogram specification"""
        lines = []
        
        # Build parameter list
        param_parts = []
        for param in subprog.parameters:
            param_str = f"{param.name} : {param.parameter_mode} {param.parameter_type.type_name}"
            if param.default_value:
                param_str += f" := {self.generate_expression(param.default_value)}"
            param_parts.append(param_str)
        
        # Build signature
        if subprog.subprogram_kind == "procedure":
            if param_parts:
                params = "; ".join(param_parts)
                signature = f"procedure {subprog.name} ({params})"
            else:
                signature = f"procedure {subprog.name}"
        else:
            if param_parts:
                params = "; ".join(param_parts)
                signature = f"function {subprog.name} ({params}) return {subprog.return_type.type_name}"
            else:
                signature = f"function {subprog.name} return {subprog.return_type.type_name}"
        
        lines.append(signature + ";")
        
        return "\n".join(lines)
    
    def generate_subprogram_body(self, body: AdaSubprogramBody) -> str:
        """Generate subprogram body"""
        lines = []
        
        # Specification part
        spec_code = self.generate_subprogram_specification(body.specification)
        spec_line = spec_code.rstrip(';')  # Remove semicolon for body
        lines.append(spec_line + " is")
        
        self.current_indent += 1
        
        # Declarations
        for decl in body.declarations:
            decl_code = self.generate_declaration(decl)
            if decl_code:
                lines.extend(self.indent_lines(decl_code.split('\n')))
        
        # Body
        lines.append("")
        lines.append("begin")
        
        for stmt in body.statements:
            stmt_code = self.generate_statement(stmt)
            if stmt_code:
                lines.extend(self.indent_lines(stmt_code.split('\n')))
        
        # Exception handlers
        if body.exception_handlers:
            lines.append("")
            lines.append("exception")
            for handler in body.exception_handlers:
                handler_code = self.generate_exception_handler(handler)
                lines.extend(self.indent_lines(handler_code.split('\n')))
        
        self.current_indent -= 1
        lines.append(f"end {body.specification.name};")
        
        return "\n".join(lines)
    
    def generate_declaration(self, decl: AdaDeclaration) -> str:
        """Generate declaration"""
        if isinstance(decl, AdaTypeDeclaration):
            return self.generate_type_declaration(decl)
        elif isinstance(decl, AdaObjectDeclaration):
            return self.generate_object_declaration(decl)
        elif isinstance(decl, AdaSubprogramSpecification):
            return self.generate_subprogram_specification(decl)
        elif isinstance(decl, AdaSubprogramBody):
            return self.generate_subprogram_body(decl)
        elif isinstance(decl, AdaTaskSpecification):
            return self.generate_task_specification(decl)
        elif isinstance(decl, AdaProtectedSpecification):
            return self.generate_protected_specification(decl)
        else:
            return f"-- Unsupported declaration: {type(decl).__name__}"
    
    def generate_type_declaration(self, type_decl: AdaTypeDeclaration) -> str:
        """Generate type declaration"""
        type_def = self.generate_type_definition(type_decl.type_definition)
        return f"type {type_decl.name} is {type_def};"
    
    def generate_type_definition(self, type_def: AdaTypeDefinition) -> str:
        """Generate type definition"""
        if isinstance(type_def, AdaRecordType):
            return self.generate_record_type(type_def)
        elif isinstance(type_def, AdaArrayType):
            return self.generate_array_type(type_def)
        elif isinstance(type_def, AdaEnumerationType):
            return self.generate_enumeration_type(type_def)
        elif isinstance(type_def, AdaAccessType):
            return f"access {type_def.designated_type.type_name}"
        elif isinstance(type_def, AdaIntegerType):
            return f"range {self.generate_expression(type_def.range_constraint.low_bound)} .. {self.generate_expression(type_def.range_constraint.high_bound)}"
        else:
            return "Integer"  # Default
    
    def generate_record_type(self, record: AdaRecordType) -> str:
        """Generate record type"""
        lines = ["record"]
        
        for component in record.components:
            comp_line = f"   {component.name} : {component.component_type.type_name};"
            lines.append(comp_line)
        
        lines.append("end record")
        return "\n".join(lines)
    
    def generate_array_type(self, array: AdaArrayType) -> str:
        """Generate array type"""
        index_types = ", ".join(idx.type_name for idx in array.index_types)
        return f"array ({index_types}) of {array.component_type.type_name}"
    
    def generate_enumeration_type(self, enum: AdaEnumerationType) -> str:
        """Generate enumeration type"""
        literals = ", ".join(enum.literals)
        return f"({literals})"
    
    def generate_object_declaration(self, obj: AdaObjectDeclaration) -> str:
        """Generate object declaration"""
        decl = f"{obj.name} : "
        
        if obj.is_constant:
            decl += "constant "
            
        decl += obj.object_type.type_name
        
        if obj.initial_value:
            decl += f" := {self.generate_expression(obj.initial_value)}"
            
        return decl + ";"
    
    def generate_task_specification(self, task: AdaTaskSpecification) -> str:
        """Generate task specification"""
        lines = [f"task type {task.name} is"]
        
        for entry in task.entries:
            lines.append(f"   entry {entry.name};")
        
        lines.append(f"end {task.name};")
        return "\n".join(lines)
    
    def generate_protected_specification(self, prot: AdaProtectedSpecification) -> str:
        """Generate protected specification"""
        lines = [f"protected type {prot.name} is"]
        
        for decl in prot.visible_declarations:
            decl_code = self.generate_declaration(decl)
            if decl_code:
                lines.append(f"   {decl_code}")
        
        lines.append(f"end {prot.name};")
        return "\n".join(lines)
    
    def generate_statement(self, stmt: AdaStatement) -> str:
        """Generate statement"""
        if isinstance(stmt, AdaAssignmentStatement):
            return f"{self.generate_expression(stmt.target)} := {self.generate_expression(stmt.value)};"
        elif isinstance(stmt, AdaProcedureCall):
            if stmt.parameters:
                params = ", ".join(self.generate_expression(p.actual_parameter) for p in stmt.parameters)
                return f"{stmt.procedure_name} ({params});"
            else:
                return f"{stmt.procedure_name};"
        elif isinstance(stmt, AdaIfStatement):
            return self.generate_if_statement(stmt)
        elif isinstance(stmt, AdaNullStatement):
            return "null;"
        else:
            return f"-- Unsupported statement: {type(stmt).__name__}"
    
    def generate_if_statement(self, if_stmt: AdaIfStatement) -> str:
        """Generate if statement"""
        lines = []
        
        lines.append(f"if {self.generate_expression(if_stmt.condition)} then")
        for stmt in if_stmt.then_statements:
            lines.append(f"   {self.generate_statement(stmt)}")
        
        for elsif_part in if_stmt.elsif_parts:
            lines.append(f"elsif {self.generate_expression(elsif_part.condition)} then")
            for stmt in elsif_part.statements:
                lines.append(f"   {self.generate_statement(stmt)}")
        
        if if_stmt.else_statements:
            lines.append("else")
            for stmt in if_stmt.else_statements:
                lines.append(f"   {self.generate_statement(stmt)}")
        
        lines.append("end if;")
        return "\n".join(lines)
    
    def generate_expression(self, expr: AdaExpression) -> str:
        """Generate expression"""
        if isinstance(expr, AdaNumericLiteral):
            return str(expr.value)
        elif isinstance(expr, AdaStringLiteral):
            return f'"{expr.value}"'
        elif isinstance(expr, AdaCharacterLiteral):
            return f"'{expr.value}'"
        elif isinstance(expr, AdaIdentifier):
            return expr.name
        elif isinstance(expr, AdaFunctionCall):
            if expr.parameters:
                params = ", ".join(self.generate_expression(p.actual_parameter) for p in expr.parameters)
                return f"{expr.function_name} ({params})"
            else:
                return expr.function_name
        else:
            return "Unknown_Expression"
    
    def generate_exception_handler(self, handler: AdaExceptionHandler) -> str:
        """Generate exception handler"""
        lines = []
        
        choices = []
        for choice in handler.exception_choices:
            if choice.exception_name:
                choices.append(choice.exception_name)
            else:
                choices.append("others")
        
        lines.append(f"when {' | '.join(choices)} =>")
        
        for stmt in handler.statements:
            stmt_code = self.generate_statement(stmt)
            lines.append(f"   {stmt_code}")
        
        return "\n".join(lines)
    
    def indent_lines(self, lines: List[str]) -> List[str]:
        """Apply current indentation to lines"""
        indent = " " * (self.current_indent * self.options.indent_size)
        return [indent + line if line.strip() else line for line in lines]
    
    def generate_generic_node(self, node: AdaNode) -> str:
        """Generate code for unknown node types"""
        return f"-- Generated from {type(node).__name__}"

# Specialized generators for different Ada styles

class SPARKGenerator(AdaGenerator):
    """SPARK-compliant Ada generator"""
    
    def __init__(self):
        options = AdaFormattingOptions(
            enforce_spark_restrictions=True,
            insert_safety_comments=True
        )
        super().__init__(AdaCodeStyle.SPARK, options)
    
    def generate_file_header(self) -> List[str]:
        """Generate SPARK-specific header"""
        header = super().generate_file_header()
        header.insert(-1, "-- SPARK 2014 Compliance Required")
        header.insert(-1, "-- No dynamic allocation, tasking restrictions apply")
        return header

class RavenscarGenerator(AdaGenerator):
    """Ravenscar profile Ada generator"""
    
    def __init__(self):
        options = AdaFormattingOptions(
            use_ravenscar_profile=True,
            insert_safety_comments=True
        )
        super().__init__(AdaCodeStyle.RAVENSCAR, options)

class DefenseGenerator(AdaGenerator):
    """Defense/aerospace standards Ada generator"""
    
    def __init__(self):
        options = AdaFormattingOptions(
            max_line_length=72,  # Stricter line length
            insert_safety_comments=True,
            align_declarations=True,
            align_assignments=True
        )
        super().__init__(AdaCodeStyle.DEFENSE, options)

# Factory functions

def create_ada_generator(style: AdaCodeStyle = AdaCodeStyle.STANDARD) -> AdaGenerator:
    """Create Ada generator with specified style"""
    if style == AdaCodeStyle.SPARK:
        return SPARKGenerator()
    elif style == AdaCodeStyle.RAVENSCAR:
        return RavenscarGenerator()
    elif style == AdaCodeStyle.DEFENSE:
        return DefenseGenerator()
    else:
        return AdaGenerator(style)

# Export main classes
__all__ = [
    'AdaGenerator', 'AdaCodeStyle', 'AdaFormattingOptions', 'AdaGenerationError',
    'SPARKGenerator', 'RavenscarGenerator', 'DefenseGenerator',
    'create_ada_generator'
] 