name: Assign Discord Sponsor Roles

on:
  schedule:
    - cron: '0 * * * *'
  workflow_dispatch:

jobs:
  assign-roles:
    runs-on: ubuntu-latest
    steps:
      - name: Sync GitHub Sponsors to Discord Roles
        uses: Alec-White/github-sponsors-discord-role-bot@v1.1
        with:
          github-token: ${{ secrets.PAT }}
          
          discord-token: ${{ secrets.DISCORD_BOT_TOKEN }}
          
          guild-id: '1428867889670258783'
          
          sponsorship-levels: |
            {
              "500": "1428869294007128104",
              "2500": "1428869229821558954",
              "10000": "1428869335383932948",
              "50000": "1429222007181934784"
            }
